#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-gamlss.dist
Version  : 6.1.1
Release  : 14
URL      : https://cran.r-project.org/src/contrib/gamlss.dist_6.1-1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/gamlss.dist_6.1-1.tar.gz
Summary  : Distributions for Generalized Additive Models for Location Scale
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
Requires: R-gamlss.dist-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package lib
Summary: lib components for the R-gamlss.dist package.
Group: Libraries

%description lib
lib components for the R-gamlss.dist package.


%prep
%setup -q -n gamlss.dist
pushd ..
cp -a gamlss.dist buildavx2
popd
pushd ..
cp -a gamlss.dist buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737145200

%install
export SOURCE_DATE_EPOCH=1737145200
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/gamlss.dist/DESCRIPTION
/usr/lib64/R/library/gamlss.dist/Distributions-2010.pdf
/usr/lib64/R/library/gamlss.dist/INDEX
/usr/lib64/R/library/gamlss.dist/Meta/Rd.rds
/usr/lib64/R/library/gamlss.dist/Meta/features.rds
/usr/lib64/R/library/gamlss.dist/Meta/hsearch.rds
/usr/lib64/R/library/gamlss.dist/Meta/links.rds
/usr/lib64/R/library/gamlss.dist/Meta/nsInfo.rds
/usr/lib64/R/library/gamlss.dist/Meta/package.rds
/usr/lib64/R/library/gamlss.dist/NAMESPACE
/usr/lib64/R/library/gamlss.dist/NEWS.md
/usr/lib64/R/library/gamlss.dist/R/gamlss.dist
/usr/lib64/R/library/gamlss.dist/R/gamlss.dist.rdb
/usr/lib64/R/library/gamlss.dist/R/gamlss.dist.rdx
/usr/lib64/R/library/gamlss.dist/doc/CentileSkewKurt.RData
/usr/lib64/R/library/gamlss.dist/doc/MomentSkewKurt1.RData
/usr/lib64/R/library/gamlss.dist/help/AnIndex
/usr/lib64/R/library/gamlss.dist/help/aliases.rds
/usr/lib64/R/library/gamlss.dist/help/gamlss.dist.rdb
/usr/lib64/R/library/gamlss.dist/help/gamlss.dist.rdx
/usr/lib64/R/library/gamlss.dist/help/paths.rds
/usr/lib64/R/library/gamlss.dist/html/00Index.html
/usr/lib64/R/library/gamlss.dist/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/gamlss.dist/libs/gamlss.dist.so
/V4/usr/lib64/R/library/gamlss.dist/libs/gamlss.dist.so
/usr/lib64/R/library/gamlss.dist/libs/gamlss.dist.so
